# -*- coding: utf-8 -*-
"""__init__

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iVCn73A-4_1-tQAHcl4QtSFN-lBwc53B
"""

"""
Пакет для чат-бота магистерских программ ИТМО

Содержит модули:
- parser - парсинг данных с сайта ИТМО
- recommender - система рекомендаций курсов
- bot - Telegram-бот
- utils - вспомогательные функции
"""

from .parser import parse_program, save_program_data, load_program_data, update_all_programs
from .recommender import CourseRecommender
from .utils import save_json, load_json

__all__ = [
    'parse_program',
    'save_program_data',
    'load_program_data',
    'update_all_programs',
    'CourseRecommender',
    'save_json',
    'load_json'
]

update_all_programs()